services:
  # PHP-FPM Application
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    container_name: zaa_radio_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    networks:
      - zaa_radio_network
    depends_on:
      - db
      - redis

  # Nginx Web Server
  web:
    image: nginx:alpine
    container_name: zaa_radio_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - zaa_radio_network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:5.7
    container_name: zaa_radio_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: zaa_radio
      MYSQL_USER: zaa_radio
      MYSQL_PASSWORD: zaa_radio_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3308:3308"
    networks:
      - zaa_radio_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: zaa_radio_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: zaa_radio
      PMA_PASSWORD: zaa_radio_password
    ports:
      - "8081:80"
    networks:
      - zaa_radio_network
    depends_on:
      - db

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: zaa_radio_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zaa_radio_network

  # Redis Commander (Redis GUI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: zaa_radio_redis_commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8082:8081"
    networks:
      - zaa_radio_network
    depends_on:
      - redis

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  zaa_radio_network:
    driver: bridge
