name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, dom, fileinfo, mysql, pdo_mysql
        
    - name: Install dependencies (with dev for tests)
      run: composer install --no-interaction --prefer-dist
      
    - name: Run tests
      run: php tests/run_tests.php
      
    - name: Security scan
      run: composer audit
      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      if: env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image
      env:
        IMAGE_NAME: ${{ secrets.DOCKER_IMAGE }}
      run: |
        IMG=${IMAGE_NAME:-zaaradio/app:latest}
        echo "Building $IMG"
        docker build -f docker/Dockerfile.prod -t $IMG .
    - name: Push image
      if: env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN && secrets.DOCKER_IMAGE
      env:
        IMAGE_NAME: ${{ secrets.DOCKER_IMAGE }}
      run: |
        IMG=${IMAGE_NAME}
        if [ -n "$IMG" ]; then
          docker push $IMG
        fi
    
    - name: Deploy to production
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          cd /var/www/zaa-radio
          git pull origin main
          ./deploy.sh

